version: '3'
services:
  web:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: reqs.txt
    restart: always
    env_file: .env
    command: bash -c "python manage.py migrate && python manage.py loaddata initial.json && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - celery-worker
    networks:
      - goodnews-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goodnews
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - goodnews-network

  rabbitmq:
    image: rabbitmq:3.9.10-management
    ports:
#      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - goodnews-network

  celery-worker:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: reqs.txt
    command: celery -A src worker --loglevel=info
    volumes:
      - ./:/app
    networks:
      - goodnews-network

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  goodnews-network:
